name: 02 - Workflow Events

on:
  # push:
  # pull_request:
  #schedule:
  #  - cron: '*/15 * * * *' # Every 15 minute. To comment as soon as possible.
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "${{ github.event_name }}"
