name: 02 - Workflow Events

on:
  push:
  pull_request:
  schedule:
    - cron: "*/5 * * * *" # Every 5 minutes. To comment as soon as possible.
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "${{ github.event_name }}"