name: 04 - Using Actions

on:
  push:

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Printing Folders
          run: |
            echo "go to 04-using-actions/react-app"
            cd 04-using-actions/react-app

            ls -la

            echo ""
            echo "public folder content"
            ls -laR public/

            echo ""
            echo "src folder content"
            ls -laR src/