name: 04 - Using Actions

on:
  push:

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Setup Node
          working-directory: 04-using-actions/react-app
          run: |
            npm ci

        - name: Printing Folders
          working-directory: 04-using-actions/react-app
          run: |
            ls -la

            echo ""
            echo "public folder content"
            ls -laR public/

            echo ""
            echo "src folder content"
            ls -laR src/