name: 06 - Contexts

on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false

# The run-name allows you to define the name of the workflow run that appears on the UI.
run-name: 06 - Contexts | DEBUG - ${{ inputs.debug }}

jobs:
  echo-data:
    runs-on: ubuntu-latest
    steps:
      - name: "Display Github info"
        run: echo "${{ toJSON(github) }}"

      - name: "Display Information"
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run number: ${{ github.run_number }}"

      - name: "Retrieve Variable"
        run: |
          #I need to create a variable "MY_VAR" in ".settings/secrets/actions" as https://github.com/sapineau/github-actions-course/settings/secrets/actions
          echo "My repository variable: ${{ vars.MY_VAR }}"