name: 07 - Using Expressions

on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        description: "debug"
        type: boolean
        default: false

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:

      - if: ${{ inputs.debug == true }}
        name: "[debug] Print start-up data"
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Runner OS: ${{ runner.os }}"

      - if: ${{ inputs.debug == true && github.ref_name == 'main' }} 
        name: "[debug] Print when triggered from main"
        run: |
          echo "I was triggered from main"

      - name: "Hello, world"
        run: |
          echo "Hello, world"