name: 13 - Using Caching

on:
  workflow_dispatch:
    inputs:
      use-cache:
          type: boolean
          description: Whether to execute cache step
          default: true
      node-version:
          type: choice
          description: Node version
          options: [18.x, 20.x, 21.x]
          default: 20.x

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        # This working directory is applied on all jobs and steps (only on run)
        working-directory: 13-caching/react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # actions/setup-node@v4.4.0 already implement caching (7 days with same version)
      - name: Setup Node
        uses: actions/setup-node@v4.4.0
        with:
          node-version: ${{ inputs.node-version }}

      - name: Download cached dependencies
        id: cache
        if: ${{ inputs.use-cache }}
        uses: actions/cache@v3
        with:
          # It's important to provide the entire path, since the working-directory option set as default at the job level applies only to run commands.
          path: 13-caching/react-app/node_modules
          # It's important to provide the entire path, we can have multiple package-lock.json in our repo. We only want this one!
          key: deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}

      - name: Install Dependencies
        # Install dependencies only if there is no cache
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Testing
        run: npm run test

      - name: Building
        run: npm run build

      - name: Deploying to nonprod
        run: echo "Deploying to nonprod"

      # There is no step for making the cache.
      # This is normal. 
      # actions/cache@v3 provide an extra step after the end of each jobs that take the content of "actions/cache@v3.path" and put it into a kvp where key = "actions/cache@v3.key"
      # next time we call the cache, it will compare the cached key with key of checkout files.
