name: 17 - 2 - Custom Actions - JS
run-name: "17 - 2 - Custom Actions - JS - Base branch '${{ inputs.base-branch }}' - Target branch '${{ inputs.target-branch }}' - Work dir '${{ inputs.working-directory }}'"

on:
  workflow_dispatch:
    inputs:
      base-branch:
        description: base branch
        type: string
        required: false
        default: main
      target-branch:
        description: target branch
        type: string
        required: false
        default: update-dependencies
      working-directory:
        description: working directory
        type: string
        required: true
        default: '17-custom-actions/react-app'
      gh-token:
        description: github token
        type: string
        required: true
      debug:
        description: use debug
        type: boolean
        default: false
        required: false

jobs:
  dependency-update:
    runs-on: ubuntu-latest
    steps:
      # The checkout is mandatory here
      # It allows to retrieve the react app AND the action.yaml file to use it.
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for dependency updates
        uses: ./.github/actions/js-dependency-update
        with:
          base-branch: ${{ inputs.base-branch }}
          target-branch: ${{ inputs.target-branch }}
          working-directory: ${{ inputs.working-directory }}
          gh-token: ${{ inputs.gh-token }}
          debug:  ${{ inputs.debug }}