name: 18 - 2 - Reusable Workflows

on:
  workflow_dispatch:

jobs:
  deploy:
    # Use full path
    uses: './.github/workflows/18-1-reusable-workflows.yaml'
    with:
      target-directory: '/app/my-app'

  print-outputs:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Print outputs
        run: |
          echo "Build status: ${{ needs.deploy.outputs.build-status }}"
          echo "URL: ${{ needs.deploy.outputs.url }}"

